### ISSUE TITLE
Unable to use mi(cover) in KWGT 

### ISSUE THREAD

**Issue by nikhilCad** [25huizengek1/ViMusic#104]
### Steps to reproduce the bug

mi(cover) is returning null

Only a lower resolution ni(mi(package), bicon) is available

### Expected behavior

mi(cover) should give a high res album art

### Actual behavior

Onlyower res ni(mi(package), bicon) is available, mi(cover) is empty string

### ViMusic version

v0.6.3

### Android version

Android 12

**Comment by nikhilCad** [comment]
Also it doesnt look like you can pin the music notification on closing the app as well, ut goes away after you close the app (compare with innertune app after enabling the media pin option in Android settings)

**Comment by Syntax-Err5** [comment]
> mi(cover) is returning null

Try enabling "show song cover" under Settings>Appearance
https://github.com/25huizengek1/ViMusic/issues/13#issuecomment-1824854667

> Also it doesnt look like you can pin the music notification on closing the app as well

As for this, could you explain a bit more? Do you mean that the music stops playing when you close the app? If so, make sure "stop when closed" is disabled under Settings>Player

Hope this helps!

**Comment by 25huizengek1** [comment]
Thank you, @Syntax-Err5, that is exactly how this could be fixed. Since you're using Android 12, you have to turn it on if you want this to work, use #13 for reference.

For the pinning stuff: the notification only stays after closing if the player is still playing, otherwise the notification gets dismissed. Make sure to turn off 'Stop when closed' though. This way the player won't stop playing when the app gets closed (service keeps running)
