### ISSUE TITLE
Material You colours

### ISSUE THREAD

**Issue by tanmaytez** [25huizengek1/ViMusic#129]
Feature request: Support for material you Colors.

I would like to request implementation of material you colors as default in every theme mode like dark/ light/ amoled or give user and option to choose.

**Comment by dtomvan** [comment]
The project has it's own UI components and as such I wouldn't recommend adding material3 as a dependency. Also, you would lose the dynamic album cover coloring...

**Comment by 25huizengek1** [comment]
While 'real' Material You is not possible (ViMusic doesn't follow Material Design principles, so a Material You color palette using the primary, onPrimary, primaryContainer, onPrimaryContainer, inversePrimary, secondary, onSecondary, secondaryContainer, onSecondaryContainer, tertiary, onTertiary, tertiaryContainer, onTertiaryContainer, background, onBackground, surface, onSurface, surfaceVariant, onSurfaceVariant, inverseSurface, inverseOnSurface and outline colors wouldn't be compatible), I think it's an interesting idea to add as a variant to the Default theme.

For the implementation part I'll first look into [MonetCompat](https://github.com/KieronQuinn/MonetCompat), because that looks like a feasible option to implement this for all supported Android versions of this project. I'll look into this later on.

**Comment by 25huizengek1** [comment]
> The project has it's own UI components and as such I wouldn't recommend adding material3 as a dependency. Also, you would lose the dynamic album cover coloring...

@dtomvan ViMusic already depends on Material 3 (M3 != Material You) for some specific components. The theming of these components is not handled by Material though.

**Comment by 25huizengek1** [comment]
Added in 3e12ac4f8ef960b0e557acd4609d519fbf926bd9
