### ISSUE TITLE
Cache album art along with songs 

### ISSUE THREAD

**Issue by divno** [25huizengek1/ViMusic#137]
## Feature request: [Downloading album art along with downloaded songs]

Would it be possible to download album art along with songs themselves instead of having to individually go through each song by listening online and download it that way. 

This could be really useful in case someone may need to move between different versions due to issues or just preferences with previous versions but doesn't want to go through the hassle every time of going through songs to download album art with their songs.

Example of individual downloading album arts since I don't think I explained it very well above: 

https://photos.app.goo.gl/y3obFGZExqLPMzQk6

**Comment by 25huizengek1** [comment]
While this is definitely possible, the app is currently not built around that idea: all shown thumbnails are fetched ‘dynamically’ for the appropriate size, which means that thumbnails that are small (in playlists, for example) are only fetched for a small size (in pixels), instead of their full quality, to save data.

This unfortunately means I’ll have to close this for now as I want to keep the thumbnail fetching as it is right now. Hope you understand.

**Comment by divno** [comment]
No problem! I completely understand
