### ISSUE TITLE
Notification or information about new publications

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#14]
At the moment new releases are displayed under discover but 99% of these artists or songs are of no interest to me.
Would it be possible to display new releases of singles and albums of the artists you have marked or have in your library to stay up to date?

**Comment by 25huizengek1** [comment]
Maybe, but I do not know if YouTube has support for that in the first place, so let me check that. If it is available I can of course implement it.

**Comment by 25huizengek1** [comment]
Well of course YouTube music supports subscribing to artists (it's YouTube), but we'll have to make a sign in option for that since you need an account for that, but then there would be no point in using this app I think, because you can probably use the regular app instead. 

For now I don't know what to do with this request. I like the idea but I do not know how to do it yet without having to log in to YouTube.

**Comment by 25huizengek1** [comment]
We could scrape the artist page of your most listened artist for example, and then get the latest uploaded songs? I don't know if that is a good user experience though...

**Comment by siggi1984** [comment]
Just a thought from me.

You are currently implementing piped.

LibreTube also runs with piped and there you can subscribe to the artists and YouTube channels.

https://github.com/libre-tube/LibreTube

**Comment by 25huizengek1** [comment]
Also a possibility, but then you would still have to log in to get this feature, which I do not particularly like.

**Comment by 25huizengek1** [comment]
Unfortunately I haven't found a good way to handle this yet. Any suggestions?

**Comment by 25huizengek1** [comment]
Closing for now as I haven’t found a good way of handling this. If anyone has a suggestion for an API or other way of getting the required data (e.g. new releases), please let me know and I’ll reopen this issue.
