### ISSUE TITLE
Better piped integration

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#55]
Thanks Bro, for the existing Piped integration. Is it possible to extend this, i.e. to create, delete and edit piped playlists with ViMusic?

**Comment by 25huizengek1** [comment]
This won't be possible, at least not with a good experience, since Piped doesn't support things like reordering, and the API seems inconsistent between Piped instances. So that is why the playlists are read-only in the app right now.

**Comment by siggi1984** [comment]
> This won't be possible, at least not with a good experience, since Piped doesn't support things like reordering, and the API seems inconsistent between Piped instances. So that is why the playlists are read-only in the app right now.

Okay, this developer here 

https://github.com/anandnet/Harmony-Music

has also integrated piped, the song reordering doesn't work there either, but the rest is very stable and reliable.

**Comment by Enigma1309** [comment]
the current piped integration only support playlist syncing,
wouldn't it be better to extend this feature and use piped as main server streaming the music,
i think that's what the piped is all about. this would be better for privacy too.

**Comment by devika15** [comment]
I would prefer if Piped is not the main server for music. I think the app
is fine the way it is.

**Comment by Enigma1309** [comment]
> I would prefer if Piped is not the main server for music. I think the app is fine the way it is.
hmm i think there should be an option for using piped as a server, maybe give the user option to `toggle` between piped and youtube, just like spottube has.
i prefer piped because of the privacy features it has and also it's quite consistent with it output things like #45 won't be present with the use of piped..

**Comment by devika15** [comment]
Yes, being able to choose would be perfect

**Comment by 25huizengek1** [comment]
I don't think I'm going to implement this because of the sheer amount of edge-cases this may cause.

For example: when listening through Piped a cache key gets created for that particular Piped instance, so listening through YouTube again won't use the cached song data. This can be avoided with some workarounds but I do not think it's viable to include this in the app, as it increases complexity.

Closing for now because of this. If there are any new ideas on how we want to deal with this I'm happy to reopen this issue and rethink my decision.
