### ISSUE TITLE
Slow pre-cache on songs

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViMusic#80]
### Steps to reproduce the bug

1- Search for any song with long length, ex: 1 hour song
2- Choose pre-cache
3- Slow and never ends

### Expected behavior

Dowloading progressive

### Actual behavior

Slow download and showing the notification forever

### Screenshots/Screen recordings

No response

### Logs

No response

### ViMusic version

0.6.2

### Android version

Android 10

### Additional information

Adding &range=0-${format.contentLength} at the end of format.url will not work either. 
Probably it need to be pre-cached in chunks (Due to the huge size, which is more than 10MB)
More than a bug, its an issue that users should be aware that they can't or they should not pre-cache big size songs, because the pre-cache service takes too long to finish. (Notification)

**Comment by 25huizengek1** [comment]
I don't know why this is a bug? Downloading a song that is an hour long takes a long time because of the size and network speeds. The progress bar indicates the sum of the downloaded amount of bytes divided by the sum of the file sizes of the queued files. You can listen to a song while it is precaching, the downloading happens in parallel, 3 songs at a time at max, retries and restarts when it fails, resumes on reboot, and the notification can be turned off.

What is it exactly that is missing here?

**Comment by th3y** [comment]
It's fixed now, thank you!
