### ISSUE TITLE
Visual glitch of progress bar and suggestions 

### ISSUE THREAD

**Issue by tanmaytez** [25huizengek1/ViMusic#84]
I've selected a song for pre cache and it has been showing the progress and notification as it's still downloading, but the song is already in offline playlist. This happens all the time 

Sometimes suggestions like artists, albums won't show up when I open the app. I tried to force restart and still it won't fix

![Screenshot_2024-01-19-12-03-04-88_6f55a3c4de83481ebdee1685416eed82.jpg](https://github.com/25huizengek1/ViMusic/assets/132748284/e7467390-0955-4d4f-8c08-7cd9a23abfaa)

**Comment by 25huizengek1** [comment]
I was aware of the weird behavior of the progress bar. Will investigate later.

**Comment by tanmaytez** [comment]
> I was aware of the weird behavior of the progress bar. Will investigate later.

Bdw, are u working on the widget?

**Comment by 25huizengek1** [comment]
> > I was aware of the weird behavior of the progress bar. Will investigate later.
> 
> Bdw, are u working on the widget?

No, tracking in #27

**Comment by 25huizengek1** [comment]
I think for consistency's sake we should just use the same logic as Exoplayer has implemented for the notification: https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/offline/DownloadNotificationHelper.java

They basically just divide the sum of the download progress of every download by the amount of downloads. I think this is not the most accurate solution, since completed downloads are filtered out the bar still jumps, like in the notification.

If we don't want this, we could just do the same and not filter out the completed downloads, but then it's not consistent with the notification again, *sigh*....

**Comment by tanmaytez** [comment]
> I think for consistency's sake we should just use the same logic as Exoplayer has implemented for the notification: https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/offline/DownloadNotificationHelper.java
> 
> They basically just divide the sum of the download progress of every download by the amount of downloads. I think this is not the most accurate solution, since completed downloads are filtered out the bar still jumps, like in the notification.
> 
> If we don't want this, we could just do the same and not filter out the completed downloads, but then it's not consistent with the notification again, *sigh*....

And why do the suggestions below the quick picks are empty

**Comment by 25huizengek1** [comment]
@tanmaytez You asked this in #83, tracking in there. Please leave questions about separate issues in their respective tickets.

**Comment by 25huizengek1** [comment]
I think, just for consistency's sake, that we should just reside to an indeterminate progress bar?

**Comment by 25huizengek1** [comment]
Fixed in a5864bb97e571681b5e1995b5247677cef2cf3e4
