### ISSUE TITLE
Weird glitch in lyrics

### ISSUE THREAD

**Issue by farzana840** [25huizengek1/ViMusic#91]
### Steps to reproduce the bug

Open the app and click on lyrics

### Expected behavior

The lyrics should scroll normally

### Actual behavior

The lyrics goes up and down each time a new line starts

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViMusic/assets/68196826/758659fd-db46-4514-961a-be6c2ec06547

### ViMusic version

0.6.3

### Android version

Android 13

### Additional information

Rest all good. Appreciate your work!

**Comment by 25huizengek1** [comment]
This looks weird, never experienced anything like this. When the lyrics gets updated, the scroll gets handled using `LazyListState::animateScrollToItem`, so nothing of this scrolling animation/behavior is actually owned by this codebase. I'll look into this, though, as it seems to be a problem because of the bigger screen of a tablet.

**Comment by 25huizengek1** [comment]
It took a bit to get it right, but this should've done the trick.

**Comment by 25huizengek1** [comment]
Please do note that this is only a workaround for the weird scrolling behavior, so this still could look a bit weird, so if that happend please let me know!
