### ISSUE TITLE
Infinite radio mode

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#95]
If the user starts a radio mode with X tracks. The playlist created by Youtube with radio mode has a certain number of tracks, it is not an infinite playlist. So my idea is that once all the tracks in the playlist the user has created with radio mode have been listened to, another radio mode is automatically started with the last track played from the playlist and that the new playlist is merged with the old playlist and the tracks are simply appended to the end of the playlist to give the user a sense of continuity without any user interaction required.

**Comment by 25huizengek1** [comment]
This already exists.

**Comment by siggi1984** [comment]
> This already exists.

When I start a radio, 24 songs are added, and after I have listened to the last song, the exact same radio starts. See screenshot. So there is no infinite radio.

![Screenshot_20240128-083603](https://github.com/25huizengek1/ViMusic/assets/103368536/8a864279-8984-4060-94a1-c2b6769c3d02)
![Screenshot_20240128-083624](https://github.com/25huizengek1/ViMusic/assets/103368536/cfcc5cef-656a-4e5e-9cb6-1a4090c21081)

**Comment by 25huizengek1** [comment]
This only happens when YouTube has ran out of suggestions. We are fetching the 'continuation' of the radio, and for the most songs this has no duplicates, but for some songs the radio is only *slightly* different, at least in my experience. Restarting the radio for the last song in the radio is not only more inconsistent, but also won't solve anything.
